services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: backend-note-list
    image: backend-note-list
    volumes:
      - ./app:/var/www
    networks:
      - laravel
    env_file:
      - ./app/.env
    entrypoint: ["/wait-for-mysql.sh", "php-fpm"]

  mysql:
    image: mysql:8.0
    container_name: mysql-note-list
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: aplikasi-note-list
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - laravel

  webserver:
    image: nginx:latest
    container_name: nginx-note-list
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app 
    networks:
      - laravel

networks:
  laravel:
