services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: backend-note-list
    volumes:
      - ./app:/var/www
    env_file:
      - .env
    networks:
      - laravel
    depends_on:
      - mysql

  webserver:
    image: nginx:latest
    container_name: nginx-note-list
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: aplikasi-note-list
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
