services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: backend-note-list
    image: backend-image
    volumes:
      - ./app:/var/www
    networks:
      - laravel

  webserver:
    image: nginx:latest
    container_name: nginx-note-list
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel: