services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: backend-note-list
    volumes:
      - ./app:/var/www
    depends_on:
      - mysql
    networks:
      - laravel

  webserver:
    image: nginx:latest
    container_name: nginx-note-list
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app 
    networks:
      - laravel

  mysql:
    image: mysql:8
    container_name: mysql-note-list
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: aplikasi-note-list
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
